server:
  port: 8080

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.ucb.edu.bo:8080/realms/DemoUCB
          jwk-set-uri: http://keycloak.ucb.edu.bo:8080/realms/DemoUCB/protocol/openid-connect/certs

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #default-filters:
      #  - TokenRelay
      routes:
        # ---- RUTA PRINCIPAL A MS-RES ----
        - id: ms-res
          uri: lb://ms-res
          predicates:
            - Path=/reviews/**
          filters:
            - StripPrefix=1

        # ---- RUTA SWAGGER MS-RES ----
        - id: ms-res-swagger
          uri: lb://ms-res
          predicates:
            - Path=/ms-res/openapi/**
          filters:
            - StripPrefix=1

        # ---- RUTAS EUREKA ----
        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

        # ---- HEALTH CHECK ----
        - id: health-ms-res
          uri: lb://ms-res
          predicates:
            - Host=microservice-health.com:8080
            - Path=/health
          filters:
            - SetPath=/actuator/health

        # ---- RUTA HACIA CONFIG-SERVER (para /encrypt, /decrypt, etc.) ----
        - id: config-server
          uri: ${spring.cloud.config.uri}
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /${segment}

app:
  eureka-server: localhost

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring:
  config:
    activate:
      on-profile: docker

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/DemoUCB
          jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs

app:
  eureka-server: eureka

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka/

