spring:
  main:
    web-application-type: reactive

  application:
    name: ms-res

  datasource:
    url: jdbc:postgresql://localhost:5432/lp_res_db
    username: postgres
    password: "{cipher}574b3957ffbe5a837e02143a667302dcf15b84a223a0d2b80dd278bba6b687ec"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/realms/DemoUCB/protocol/openid-connect/certs

app:
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 7003
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.ucb.plataforma.res.reviews: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres_res:5432/lp_res_db
    username: postgres
    password: "{cipher}574b3957ffbe5a837e02143a667302dcf15b84a223a0d2b80dd278bba6b687ec"
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs

app:
  eureka-server: eureka

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka/

server:
  port: 8080
